apiVersion: v1
kind: Service
metadata:
  name: grupo8-api-gateway
spec:
  type: NodePort
  selector:
    app: grupo8-api-gateway
  ports:
    - port: 5000
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupo8-api-gateway
spec:
  selector:
    matchLabels:
      app: grupo8-api-gateway
  template:
    metadata:
      labels:
        app: grupo8-api-gateway
    spec:
      containers:
      - name: grupo8-api-gateway
        image: janjorquera/api-gateway:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"