services:
  demo_04_api_gateway:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/code
    environment:
      - SEARCH_SERVICE_BASE=https://searchservice.inf326.nursoft.dev
      - CHANNEL_SERVICE_BASE=https://channel-api.inf326.nur.dev/v1/channels
      - MESSAGE_SERVICE_BASE=https://messages-service.kroder.dev
    network_mode: "host"

networks:
  default:
    name: demo_04
    external: true